name: Lighthouse CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1' # Mondays 07:00 UTC

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.13.x

      - name: Run Lighthouse CI (production URL)
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          lhci autorun \
            --collect.url=https://millerms.github.io/CranburyChiropractic/ \
            --collect.numberOfRuns=3 \
            --assert.preset=lighthouse:recommended \
            --assert.budgetsFile=./lighthouse/budgets.json || echo "LHCI completed with non-zero exit (assertions may have failed)."

